[template]
src="syncthings.csv.tmpl"
dest="/opt/cloudify/syncthing/syncthings.csv"

mode="0644"
keys = [
  "/syncthing",
]
reload_cmd = "python /opt/cloudify/syncthing/rerender.py && systemctl restart cloudify-syncthing"
